import React from 'react';
import { useRouter } from 'next/router';
import {
  totalStickers,
  waterSaved,
  electricitySaved,
  co2Saved,
  flyersReduced,
} from '../../utils/calculations';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faHouseUser,
  faWater,
  faTree,
  faLightbulb,
  faCloud,
} from '@fortawesome/free-solid-svg-icons';
import useSWR from 'swr';
import { ISticker } from '../../services/type';
import { getStickers } from '../../services/repository/getStickers';
import axios from 'axios';

interface IStatistics {
  stickers: ISticker[];
}

export default function Statistics({ stickers }) {
  const router = useRouter();

  const { data } = useSWR(
    '/api/stickers/',
    () => {
      return axios.get('/api/stickers/').then((res) => res.data);
    },
    {
      fallbackData: stickers,
    }
  );

  return (
    <div id="portfolio" className="h-100 text-center justify-content-center">
      <div className="row">
        <div className="offset-md-2 col-md-8">
          <span className="preTitle">How We Help</span>
          <h2>
            {router.locale === 'en'
              ? 'ecotowari In Numbers'
              : '数字で見るecotowari'}
          </h2>
          <pre>
            {router.locale === 'en' ? (
              <>
                <p>
                  A single ecotowari sticker helps reduce waste generated by
                  brochures by 85 grammes per week on average (tests done in the
                  Tokyo region). It might not seem like much in itself but
                  imagine the impact that all the ecotowari stickers together
                  are having...
                </p>
                <p>
                  No need to imagine it! We have laid it out below in our
                  real-time impact generator ↓
                </p>
              </>
            ) : (
              <>
                <p>
                  東京都内で行った実証実験によると、ecotowariステッカー１枚あたり、一週間で平均85gのチラシの無駄遣いを減らすことができます。一枚だとそこまで大きな効果があるように感じませんが、全てのecotowariステッカーによる効果を想像してみてください。
                </p>
                <p>
                  全てのecotowariステッカーにより、どれほどの資源が守られているか見てみよう！
                </p>
              </>
            )}
          </pre>
        </div>
      </div>
      <div className="row justify-content-center align-items-center pt-4">
        <div className="col-md-4">
          <div className="card text-primary">
            <FontAwesomeIcon
              icon={faHouseUser}
              size="lg"
              className="circle-icon"
            />
            <h3 className="text-primary">{Math.round(totalStickers(data))}</h3>
            <h6>
              {router.locale === 'en'
                ? 'Stickers in place'
                : 'ステッカー使用数'}
            </h6>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card">
            <FontAwesomeIcon icon={faTree} size="lg" className="circle-icon" />
            <h3 className="text-primary">
              {Math.round(flyersReduced(data))} kg
            </h3>
            <h6>
              {router.locale === 'en'
                ? 'Paper waste reduced'
                : '削減されたチラシ'}
            </h6>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card text-primary">
            <FontAwesomeIcon icon={faWater} size="lg" className="circle-icon" />
            <h3 className="text-primary">{Math.round(waterSaved(data))} L</h3>
            <h6>
              {router.locale === 'en' ? 'Water saved' : 'リットルの水を節約'}
            </h6>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card">
            <FontAwesomeIcon
              icon={faLightbulb}
              size="lg"
              className="circle-icon"
            />
            <h3 className="text-primary">
              {Math.round(electricitySaved(data))} kWh
            </h3>
            <h6>
              {router.locale === 'en' ? 'Electricity saved' : '省エネルギー'}
            </h6>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card">
            <FontAwesomeIcon icon={faCloud} size="lg" className="circle-icon" />
            <h3 className="text-primary">
              {Math.round(co2Saved(data))} kg-CO2e
            </h3>
            <h6>{router.locale === 'en' ? 'CO₂ saved' : '削減されたCO₂'}</h6>
          </div>
        </div>
      </div>
    </div>
  );
}
