import React, {ReactElement} from 'react'
import PropTypes from 'prop-types'
import {useRouter} from 'next/router'

import MainLayout from '../features/layout/mainLayout'
import Container from '../components/Container'
import HeroHeader from '../components/header/HeroHeader'
import GetStickerCTA from '../features/sections/GetStickerCTA'
import Supabase from '../utils/supabase'
import client from '../client'
import groq from 'groq'
import FollowUs from '../features/sections/FollowUs'

export async function getStaticProps() {
  // get i18n text from sanity
  const homePage = await client.fetch(groq`
      *[_type == "home-page"]{'aboutImage': aboutsection.image.asset->url, ...} | order(publishedAt desc)
    `)
  const {data: stickers, error} = await Supabase.from('stickers').select('qty, started_at')
  if (error) {
    throw new Error(error.message)
  }

  return {
    props: {
      stickers,
      homePage,
    },
  }
}

Mission.propTypes = {
  stickers: PropTypes.arrayOf(PropTypes.object),
  homePage: PropTypes.arrayOf(PropTypes.object),
}

function Mission({stickers, homePage}) {
  const {ctasection, followsection} = homePage[0]
  const router = useRouter()
  console.log(router)

  return (
    <>
      <Container wrapperClass="header-wrapper">
        <HeroHeader title={'Reducing Waste By Refusing Waste'} />
      </Container>

      {/* About Ecotowari */}
      <Container wrapperClass="d-flex " pretitle="About ecotowari" title="Our Mission">
        <p>
          While papermaking and printing companies have made efforts over the years, paper
          manufacturing still requires large quantities of water, wood, energy and chemical
          products. For more details about the extent of the problem, check out the dedicated
          section on the environmental impact of flyers.
        </p>
        <p>
          ecotowari is an initiative to tackle the waste generated by flyers through a mailbox
          sticker. The sticker indicates in positive, clear terms that you do not wish to receive
          flyers because you care about our planet. Simple as that. With tests carried out all
          around Tokyo, we have seen reduction rates of over 99%. Our early supporters have received
          virtually 0 flyers.
        </p>
        <p>
          With a cute and efficient sticker working for you in the background, you know that the
          next time you will open your mailbox, it will be to see the mail that matters!
        </p>
      </Container>

      {/* Our Story */}
      <Container
        wrapperClass="d-flex align-items-center bg-2"
        pretitle="Our Story"
        title="How We Started"
      >
        <p>The initiative was launched in January 2022 in a sharehouse in Nippori, Tokyo. </p>
        <p>
          Founder Rémy Millot recalls: “Ever since I settled into my new home in Tokyo, I found the
          number of flyers pouring into my mailbox quite overwhelming. As a quick fix that somehow
          became permanent (as all quick fixes tend to be?) I put together some paper tape and a
          note saying I didn’t want to receive flyers. And much to my surprise, that very
          homemade-looking sticker proved to be working.
        </p>
        <p>
          My other housemates would also complain about receiving too many flyers. They liked the
          idea of a sticker but didn’t want it to be some homemade paper tape. That’s when I
          realized we needed a “proper” sticker if we wanted this type of initiative to pick up and
          grow. ecotowari was born!”{' '}
        </p>
        <p>
          The name ecotowari is a new word bringing together the words eco and kotowari, Japanese
          word for “refusing”. ecotowari means turning down single-use items for environmental
          reasons.
        </p>
      </Container>

      {/* How We Are Different */}
      <Container
        wrapperClass="d-flex align-items-center"
        pretitle="How We Are Different"
        title="What Makes ecotowari Unique?"
      >
        <p>
          We didn&apos;t invent the “チラシお断り” (chirashi okotowari – no to flyers) stickers.
          They have indeed been around for a while and one can already see them on mailboxes here
          and there. However, we were unhappy with their design as no mention is made of the
          environment or waste reduction. They include very strong language such as
          &quot;you&apos;re being watched&quot; or &quot;we will report you to the police&quot;. We
          feel this type of wording is a barrier to a wider adoption and discourages people from
          putting them on their mailboxes.
        </p>
        <p>
          Our goal with ecotowari is to use a different kind of symbolism and language in order to
          create an inclusive and positive movement - for the planet - instead of the
          anti-anythingthatcomesnearmydoor approach.
        </p>
        <p>
          And the best thing about our stickers is that they’re just as efficient with over 99%
          reduction rates 😊
        </p>
        <p>Join the movement and brighten up your mailbox with an ecotowari sticker!</p>
      </Container>

      {/* Positive Impact */}
      <Container
        wrapperClass="d-flex align-items-center bg-2 text-center"
        pretitle="How we Help"
        title="ecotowari In Numbers"
      >
        <p>
          A single ecotowari sticker helps reduce waste generated by brochures by 85 grammes per
          week on average (tests done in the Tokyo region). It might not seem like much in itself
          but imagine the impact that all the ecotowari stickers together are having... No need to
          imagine it! We have laid it out below in our real-time impact generator ↓
        </p>
        <p>[new statistic cards will go here]</p>
      </Container>

      {/* CTA */}
      <Container wrapperClass="header-wrapper d-flex align-items-center bg-3">
        <GetStickerCTA data={ctasection} />
      </Container>

      {/* Socials */}
      <Container wrapperClass="d-flex align-items-center bg-2">
        <FollowUs data={followsection} />
      </Container>

      {/* FAQ */}
      {/* <Container
        wrapperClass="min-h-100 d-flex align-items-center bg-2 text-center"
        pretitle="FAQ"
        title="Common Questions"
      >
        <FAQ />
      </Container> */}
    </>
  )
}

// Get the main template for standard pages
Mission.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>
}

export default Mission
