import React from 'react'
import PropTypes from "prop-types"
import {useRouter} from 'next/router'

EnvironmentImpact.propTypes = {
  data: PropTypes.object
}

export default function EnvironmentImpact({data}) {
  const router = useRouter()

  return (
    <div className="row">
      <span className="text-center preTitle">Why ecotowari</span>
      <h2 className="text-center">{data.title[router.locale]}</h2>
      <p>
      And even if they seem free – flyers have a tremendous environmental cost.
The process to create flyers requires a lot of water resources, deforestation, electric power, chemicals and cause CO2 emission. (For more details, check Research & data page)

A single ecotowari sticker helps reduce waste generated by brochures up to XX kg per year so imagine the impact that all the ecotowari stickers together are having.

Get a sticker now and join a growing movement of hundreds!
      </p>
        <div className="col-md-6 p-5 border">
          <pre>{data.water[router.locale]}</pre>
        </div>
        <div className="col-md-6 p-5 border">
          <pre>{data.electricity[router.locale]}</pre>
        </div>
        <div className="col-md-6 p-5 border">
            <pre>{data.chemicals[router.locale]}</pre>
        </div>
        <div className="col-md-6 p-5 border">
          <pre>{data.wood[router.locale]}</pre>
        </div>
      </div>
  )
}
